%%
clear
clc

load('S7_2_bestK_rbf.mat')%variable name: bestK_rbf
load('S7_2_rmse_Nminus1_rbf.mat')%variable name: rmse_Nminus1_rbf
rmse_rbf = rmse_Nminus1;
load('S7_2_rmse_all_rbf.mat');%variable name: rmse_all_rbf
rmse_rbf_all = rmse_all;
Feature_label = {'Logo-Frontal-Mid-L','Logo-Frontal-Mid-R',...
    'Logo-Frontal-Inf-Oper-L','Logo-Frontal-Inf-Oper-R',...
    'Logo-Frontal-Inf-Tri-L','Logo-Frontal-Inf-Tri-R',...
    'Logo-Precentral-L','Logo-Precentral-R',...
    'Logo-Supp-Motor-L','Logo-Supp-Motor-R',...
    'Logo-Parietal-Inf-L','Logo-Parietal-Inf-R',...
    'Logo-SupraMarginal-L','Logo-SupraMarginal-R',...
    'Logo-Angular-L','Logo-Angular-R',...
    'Logo-Temporal-Sup-L','Logo-Temporal-Sup-R',...
    'Logo-Temporal-Pole-Sup-Mid-L','Logo-Temporal-Pole-Sup-Mid-R',...
    'Logo-Temporal-Mid-L','Logo-Temporal-Mid-R',...
    'Logo-Fusiform-L','Logo-Fusiform-R',...
    'Logo-Occipital-Sup-L','Logo-Occipital-Mid-L',...
    'Logo-Occipital-Inf-L','Logo-Occipital-Sup-R',...
    'Logo-Occipital-Mid-R','Logo-Occipital-Inf-R',...
    'Pho-Frontal-Mid-L','Pho-Frontal-Mid-R',...
    'Pho-Frontal-Inf-Oper-L','Pho-Frontal-Inf-Oper-R',...
    'Pho-Frontal-Inf-Tri-L','Pho-Frontal-Inf-Tri-R',...
    'Pho-Precentral-L','Pho-Precentral-R',...
    'Pho-Supp-Motor-L','Pho-Supp-Motor-R',...
    'Pho-Parietal-Inf-L','Pho-Parietal-Inf-R',...
    'Pho-SupraMarginal-L','Pho-SupraMarginal-R',...
    'Pho-Angular-L','Pho-Angular-R',...
    'Pho-Temporal-Sup-L','Pho-Temporal-Sup-R',...
    'Pho-Temporal-Pole-Sup-Mid-L','Pho-Temporal-Pole-Sup-Mid-R',...
    'Pho-Temporal-Mid-L','Pho-Temporal-Mid-R',...
    'Pho-Fusiform-L','Pho-Fusiform-R',...
    'Pho-Occipital-Sup-L','Pho-Occipital-Mid-L',...
    'Pho-Occipital-Inf-L','Pho-Occipital-Sup-R',...
    'Pho-Occipital-Mid-R','Pho-Occipital-Inf-R',...
    'Sem-Frontal-Mid-L','Sem-Frontal-Mid-R',...
    'Sem-Frontal-Inf-Oper-L','Sem-Frontal-Inf-Oper-R',...
    'Sem-Frontal-Inf-Tri-L','Sem-Frontal-Inf-Tri-R',...
    'Sem-Precentral-L','Sem-Precentral-R',...
    'Sem-Supp-Motor-L','Sem-Supp-Motor-R',...
    'Sem-Parietal-Inf-L','Sem-Parietal-Inf-R',...
    'Sem-SupraMarginal-L','Sem-SupraMarginal-R',...
    'Sem-Angular-L','Sem-Angular-R',...
    'Sem-Temporal-Sup-L','Sem-Temporal-Sup-R',...
    'Sem-Temporal-Pole-Sup-Mid-L','Sem-Temporal-Pole-Sup-Mid-R',...
    'Sem-Temporal-Mid-L','Sem-Temporal-Mid-R',...
    'Sem-Fusiform-L','Sem-Fusiform-R',...
    'Sem-Occipital-Sup-L','Sem-Occipital-Mid-L',...
    'Sem-Occipital-Inf-L','Sem-Occipital-Sup-R',...
    'Sem-Occipital-Mid-R','Sem-Occipital-Inf-R',...
    };

kk_rbf = sort(rmse_Nminus1,'ascend');
[lia, locb_rbf] = ismember(kk_rbf(end-16:end), rmse_rbf);
% h = bar(kk_rbf(1,1:38),0.9);box off;
% subplot(1,2,2);
yy = zeros(45,45);
for i = 1:45
    yy(2*i-1,2*i-1) = kk_rbf(1,2*i-1);
    h1 = barh(yy(2*i-1,:),'BarWidth',0.7,'FaceColor',[240 128 128]/255);
    hold on;
    yy(2*i,2*i) = kk_rbf(1,2*i);
    h2 = barh(yy(2*i,:),'BarWidth',0.7,'FaceColor',[238 233 233]/255);
    hold on;
end
set(gca,'xlim',[0.14,0.165]);
set(gca,'xtick',[0.14 0.16]);
set(gca,'ytick',[ ]);
set(gca,'ylim',[77.5,90.5]);
box off;
xlabel('rmse','fontsize',12,'fontweight','bold');
hold on;
for id = 1:13
    text(0.14-0.0001,91-id,Feature_label{locb_rbf(18-id)},...
        'HorizontalAlignment','right','Fontsize',6);hold on;
end
% 6*9 inches, 600dpi, scale min7.5points, 1.5 pounds line
%%
%-----------
plot([1:38],bestK_rbf(1:38)*-1,'Color',[154 205 50]/255);hold on;
plot([0,40],[rmse_rbf_all*-1,rmse_rbf_all*-1],'k','linestyle','--');hold on;
scatter(13,bestK_rbf(1,13)*-1,[],[154 205 50]/255,'o','filled');box off;
set(gca,'xtick',[0:10:40]);
set(gca,'ylim',[-0.45 0]);set(gca,'ytick',[-0.45:0.15:0]);
ylabel('-rmse','fontsize',12,'fontweight','bold');
text(13,-0.1,'best N = 13','HorizontalAlignment','center');
% 
